package bioproject;

import static bioproject.MainPage.five;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.*;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author Nize
 */
public class Five extends javax.swing.JFrame {

    int count = 0;
    static int c = 0;
    static String ANS = "";

    public Five() {
        initComponents();
        getIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("แปลงรหัส DNA หรือ mRNA เป็นกรดะอมิโน");
        setMaximumSize(new java.awt.Dimension(732, 499));
        setMinimumSize(new java.awt.Dimension(732, 499));
        setPreferredSize(new java.awt.Dimension(732, 530));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 160, 40, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 220, 270, 50);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 460, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("กรอกสาย DNA หรือ mRNA ที่ต้องการแปลง");
        jTextArea1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextArea1CaretUpdate(evt);
            }
        });
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 40, 640, 160);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 290, 650, 160);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 10, 110, 30);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(690, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/05.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1120, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainPage m = new MainPage();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jTextArea1.setText("กรอกสาย DNA หรือ mRNA ที่ต้องการแปลง");
        count = 0;
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        if (count == 0) {
            jTextArea1.setText("");
        }
        count++;
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        if (count == 0) {
            jTextArea1.setText("");
        }
        count++;
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String txt = jTextArea1.getText();
        String tmp;
        if (txt.length() > 0 && txt.charAt(0) != 'ก') {
            Algorithms a = new Algorithms();
            String t = txt.replaceAll("\n", "");
            if (!a.CheckError(t)) {
                c = 0;
                ANS = "";
                tmp = a.ChangeDNAToAminoAcid(t);
                jTextArea2.setText(tmp);
                getCo(tmp);
            } else if (JOptionPane.showConfirmDialog(null, "สายข้อมูลนำเข้ามีข้อผิดพลาด\nหากดำเนินการต่ออาจมีข้อผิดพลาด\n"
                    + "ต้องการดำเนินการต่อหรือไม่", "แจ้งเตือน",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                c = 0;
                ANS = "";
                tmp = a.ChangeDNAToAminoAcid(t);
                jTextArea2.setText(tmp);
                getCo(tmp);
            } else {
                jTextArea2.setText("N/A");
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "กรุณากรอกสาย DNA หรือ mRNA ที่ต้องการแปลง", "แจ้งเตือน",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLabel3MouseClicked
    public void getCo(String a) {
        Highlighter.HighlightPainter cyanPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.cyan);
        Highlighter.HighlightPainter redPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.red);
        String tmp = a;
        Pattern p = Pattern.compile("Met");
        Matcher m = p.matcher(tmp);
        while (m.find()) {
            try {
                jTextArea2.getHighlighter().addHighlight(m.start(), m.end(), cyanPainter);
            } catch (BadLocationException ex) {
                System.out.println("Not found.");
            }
        }
        p = Pattern.compile("Stop");
        m = p.matcher(tmp);
        while (m.find()) {
            try {
                jTextArea2.getHighlighter().addHighlight(m.start(), m.end(), redPainter);
            } catch (BadLocationException ex) {
                System.out.println("Not found.");
            }
        }
    }
    public void getCo1(String a) {
        Highlighter.HighlightPainter cyanPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.cyan);
        Highlighter.HighlightPainter redPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.red);
        Pattern p = Pattern.compile("[^atgcuATGCU\n]");
        Matcher m = p.matcher(a);
        while (m.find()) {
            try {
                jTextArea1.getHighlighter().addHighlight(m.start(), m.end(), redPainter);
            } catch (BadLocationException ex) {
                System.out.println("Not found.");
            }
        }
    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jTextArea2.setText("");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jTextArea1.setText("ATGCGCTCTCTTTCAGCATTCGTCTTCCTCTCGGTCATCGTCGGCACA\n"
                + "TATGGCGCAATAGGTCCAAGCACCAGTCTTTACATCGCAAACAAGTAC\n"
                + "ATCCTCCCCGATGGATTCAACCGCTCTAGTGTTTTGGCAGGTCCCACT\n"
                + "GCAGCAAATGTATCATTCCCTGGTCCTGTTATCACTGGCTTCCAGGGA\n"
                + "GATACATTTAGCATTAATGTCATCGATCAACTCACTGATACTACAATG\n"
                + "TTGACGAGCACTAGTCTTCACTGGCATGGCCTGTTCTAAGAAGGTAGT");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        About05 ab = new About05();
        ab.setVisible(true);
        five.setEnabled(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextArea1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextArea1CaretUpdate
        getCo1(jTextArea1.getText());
    }//GEN-LAST:event_jTextArea1CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Five().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    private void getIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.ico")));
    }
}
