package bioproject;

import static bioproject.MainPage.four;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Nize
 */
public class Four extends javax.swing.JFrame {

    int count = 0, count1 = 0;
    static String codon[] = {"UUU", "UCU", "UAU", "UGU", "UUC", "UCC", "UAC", "UGC", "UUA", "UCA", "UAA", "UGA", "UUG", "UCG", "UAG", "UGG", "CUU", "CCU", "CAU", "CGU", "CUC", "CCC", "CAC", "CGC", "CUA", "CCA", "CAA", "CGA", "CUG", "CCG", "CAG", "CGG", "AUU", "ACU", "AAU", "AGU", "AUC", "ACC", "AAC", "AGC", "AUA", "ACA", "AAA", "AGA", "AUG", "ACG", "AAG", "AGG", "GUU", "GCU", "GAU", "GGU", "GUC", "GCC", "GAC", "GGC", "GUA", "GCA", "GAA", "GGA", "GUG", "GCG", "GAG", "GGG"};
    static String shname[] = {"Phe", "Ser", "Tyr", "Cys", "Phe", "Ser", "Tyr", "Cys", "Leu", "Ser", "Stop", "Stop", "Leu", "Ser", "Stop", "Trp", "Leu", "Pro", "His", "Arg", "Leu", "Pro", "His", "Arg", "Leu", "Pro", "Gln", "Arg", "Leu", "Pro", "Gln", "Arg", "Ile", "Thr", "Asn", "Ser", "Ile", "Thr", "Asn", "Ser", "Ile", "Thr", "Lys", "Arg", "Met", "Thr", "Lys", "Arg", "Val", "Ala", "Asp", "Gly", "Val", "Ala", "Asp", "Gly", "Val", "Ala", "Glu", "Gly", "Val", "Ala", "Glu", "Gly"};
    static char yor[] = {'F', 'S', 'Y', 'C', 'F', 'S', 'Y', 'C', 'L', 'S', '*', '*', 'L', 'S', '*', 'W', 'L', 'P', 'H', 'R', 'L', 'P', 'H', 'R', 'L', 'P', 'Q', 'R', 'L', 'P', 'Q', 'R', 'I', 'T', 'N', 'S', 'I', 'T', 'N', 'S', 'I', 'T', 'K', 'R', 'M', 'T', 'K', 'R', 'V', 'A', 'D', 'G', 'V', 'A', 'D', 'G', 'V', 'A', 'E', 'G', 'V', 'A', 'E', 'G'};
    static String engname[] = {"Phenylalanin", "Serine", "Tyrosine", "Cysteine", "Phenylalanin", "Serine", "Tyrosine", "Cysteine", "Leucine", "Serine", "Stop (Ochre)", "Stop (Opal)", "Leucine", "Serine", "Stop (Amber)", "Tryptophan", "Leucine", "Proline", "Histidine", "Arginine", "Leucine", "Proline", "Histidine", "Arginine", "Leucine", "Proline", "Glutamine", "Arginine", "Leucine", "Proline", "Glutamine", "Arginine", "Isoleucine", "Threonine", "Asparagine", "Serine", "Isoleucine", "Threonine", "Asparagine", "Serine", "Isoleucine", "Threonine", "Lysine", "Arginine", "Methionine", "Threonine", "Lysine", "Arginine", "Valine", "Alanine", "Aspartic acid", "Glycine", "Valine", "Alanine", "Aspartic acid", "Glycine", "Valine", "Alanine", "Glutamic acid", "Glycine", "Valine", "Alanine", "Glutamic acid", "Glycine"};
    static String thname[] = {"ฟีนิลอะลานีน", "ซีรีน", "ไทโรซีน", "ซีสเทอีน", "ฟีนิลอะลานีน", "ซีรีน", "ไทโรซีน", "ซีสเทอีน", "ลิวซีน", "ซีรีน", "*", "*", "ลิวซีน", "ซีรีน", "*", "ทริปโตเฟน", "ลิวซีน", "โพรลีน", "ฮีสทีดีน", "อาร์จีนีน", "ลิวซีน", "โพรลีน", "ฮีสทีดีน", "อาร์จีนีน", "ลิวซีน", "โพรลีน", "กลูตามีน", "อาร์จีนีน", "ลิวซีน", "โพรลีน", "กลูตามีน", "อาร์จีนีน", "ไอโซลิวซีน", "ทรีโอนีน", "แอสพาราจีน", "ซีรีน", "ไอโซลิวซีน", "ทรีโอนีน", "แอสพาราจีน", "ซีรีน", "ไอโซลิวซีน", "ทรีโอนีน", "ไลซีน", "อาร์จีนีน", "เมไทโอนีน", "ทรีโอนีน", "ไลซีน", "อาร์จีนีน", "วาลีน", "อะลานีน", "กรดแอสปาติก", "ไกลซีน", "วาลีน", "อะลานีน", "กรดแอสปาติก", "ไกลซีน", "วาลีน", "อะลานีน", "กรดกลูตามิก", "ไกลซีน", "วาลีน", "อะลานีน", "กรดกลูตามิก", "ไกลซีน"};

    public Four() {
        initComponents();
        getIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ตาราง Genetic code");
        setMaximumSize(new java.awt.Dimension(732, 499));
        setMinimumSize(new java.awt.Dimension(732, 499));
        setPreferredSize(new java.awt.Dimension(732, 530));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 70, 40, 40);

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("DNA / mRNA / ชื่อ");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 70, 160, 35);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 460, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 120, 100, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 160, 90, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 250, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 290, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 360, 270, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 200, 110, 50);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/04.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainPage m = new MainPage();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        JOptionPane.showMessageDialog(this,
                "   ลำดับเบสบนสาย mRNA จะเป็นตัวกำหนดลำดับกรดอะมิโนสำหรับสาย พอลิเพปไทด์ \n"
                + "ซึ่งลำดับเบสที่เป็นตัวกำหนดชนิดของกรดอะมิโนนี้ เรียกว่า “รหัสพันธุกรรม (genetic code)”\n"
                + "โดยลำดับเบส 3 ตัว ที่เรียงติดกันจะเป็นตัวกำหนดชนิดของกรดอะมิโน 1 ตัว\n"
                + "จึงเรียกรหัสพันธุกรรมว่า “รหัสชุดสาม (Triplet code หรือ Codon)” \n"
                + "และเนื่องจากว่ามีเบสอยู่แค่ 4 ชนิด (G, A, U และ C) บนสาย mRNA \n"
                + "เมื่อนำมาจัดกลุ่มแบบเรียงทีละ 3 เบสจะได้รหัสชุดสามทั้งหมดเป็น 4 ยกกำลัง 3 = 64 Codons\n"
                + "ที่มีการเรียงลำดับเบสต่างกัน ดังนั้นรหัสพันธุกรรมจึงมีได้ทั้งหมด 64 Codons หรือ 64 รหัส\n"
                + "ซึ่งในจำนวน 64 รหัสนี้ มีเพียง 61 รหัสเท่านั้น ที่เป็นรหัสของกรดอะมิโนทั้ง 20 ชนิด\n"
                + "เพราะอีก 3 รหัสที่เหลือ คือ UAA, UAG และ UGA จะเป็น “รหัสยุติ”\n"
                + "(Termination codon หรือ Stop codon) ซึ่งไม่ได้เป็นรหัสของกรดอะมิโนชนิดใดเลย\n"
                + "แต่ทำหน้าที่เป็นสัญญาณสำหรับหยุดการสังเคราะห์โปรตีน", "เกี่ยวกับรหัสพันธุกรรม",
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jTextField1.setForeground(Color.GRAY);
        count = 0;
        String str = jTextField1.getText();
        jTextField1.setText(str);
        if (str.length() > 0 && str.charAt(0) != 'D') {
            Algorithms al = new Algorithms();
            int tmp = al.Search(str.toUpperCase());

            if (tmp != -1) {
                jLabel5.setForeground(Color.yellow);
                jLabel6.setForeground(Color.yellow);
                jLabel7.setForeground(Color.yellow);
                jLabel8.setForeground(Color.yellow);
                jLabel9.setForeground(Color.yellow);
                jLabel11.setForeground(Color.yellow);
                jLabel5.setText(codon[tmp]);
                jLabel6.setText(yor[tmp] + "");
                jLabel7.setText(thname[tmp]);
                jLabel8.setText(engname[tmp]);
                jLabel9.setText(al.SameCodon(tmp));
                jLabel11.setText(shname[tmp]);

            } else {
                tmp = al.Search(al.DNATomRNA(str).toUpperCase());
                if (tmp != -1) {
                    jLabel5.setForeground(Color.yellow);
                    jLabel6.setForeground(Color.yellow);
                    jLabel7.setForeground(Color.yellow);
                    jLabel8.setForeground(Color.yellow);
                    jLabel9.setForeground(Color.yellow);
                    jLabel11.setForeground(Color.yellow);
                    jLabel5.setText(codon[tmp]);
                    jLabel6.setText(yor[tmp] + "");
                    jLabel7.setText(thname[tmp]);
                    jLabel8.setText(engname[tmp]);
                    jLabel9.setText(al.SameCodon(tmp));
                    jLabel11.setText(shname[tmp]);
                } else {
                    jLabel5.setForeground(Color.RED);
                    jLabel6.setForeground(Color.BLACK);
                    jLabel7.setForeground(Color.BLACK);
                    jLabel8.setForeground(Color.BLACK);
                    jLabel9.setForeground(Color.BLACK);
                    jLabel11.setForeground(Color.BLACK);
                    jLabel5.setText("N/A");
                    jLabel6.setText(" -");
                    jLabel7.setText(" -");
                    jLabel8.setText(" -");
                    jLabel9.setText(" -");
                    jLabel11.setText(" -");
                    JOptionPane.showMessageDialog(this,
                            "ไม่พบรายการ กรุณาลองใหม่อีกครั้ง", "แจ้งเตือน",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "กรุณากรอก DNA , mRNA หรือ ชื่อกรดอะมิโนที่ต้องค้นหา", "แจ้งเตือน",
                    JOptionPane.WARNING_MESSAGE);
        }
        jTextField1.setText("DNA / mRNA / ชื่อ");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (count == 0) {
            jTextField1.setText("");
            jTextField1.setForeground(Color.BLACK);
        }
        count++;
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
        jLabel5.setForeground(Color.BLACK);
        jLabel6.setForeground(Color.BLACK);
        jLabel7.setForeground(Color.BLACK);
        jLabel8.setForeground(Color.BLACK);
        jLabel9.setForeground(Color.BLACK);
        jLabel11.setForeground(Color.BLACK);
        jLabel5.setText(" -");
        jLabel6.setText(" -");
        jLabel7.setText(" -");
        jLabel8.setText(" -");
        jLabel9.setText(" -");
        jLabel11.setText(" -");

    }//GEN-LAST:event_jTextField1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        About04 ab = new About04();
        ab.setVisible(true);
        four.setEnabled(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Four().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void getIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.ico")));
    }
}
